### ISSUE TITLE
Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1

### ISSUE THREAD

**Issue by lxw0109** [sanathp/DatabaseManager_For_Android#18]
It works well when no database upgrades. But I got the following errors after upgrading the database(by `dbHelper = new MyDatabaseHelper(this, "BookStore.db", null, 2)`):
`
11-14 09:57:08.108 23201-23201/com.xlab.iscas.databasetest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xlab.iscas.databasetest/com.xlab.iscas.databasetest.AndroidDatabaseManager}: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2097)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:140)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
                                                                                 at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
                                                                                 at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
                                                                                 at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                                 at com.xlab.iscas.databasetest.MyDatabaseHelper.getData(MyDatabaseHelper.java:67)
                                                                                 at com.xlab.iscas.databasetest.AndroidDatabaseManager.onCreate(AndroidDatabaseManager.java:246)
                                                                                 at android.app.Activity.performCreate(Activity.java:5163)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2061)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122) 
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1228) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
`
Does anybody help?

**Comment by sanathp** [comment]
Does your helper override downgrade method ?

Check this for more info 
http://stackoverflow.com/questions/24053786/cant-downgrade-database-from-version-2-to-1-even-after-fresh-install-and-re-run
